### PR TITLE
Fix typo in lib.rs

### LINKED ISSUE #202: Typo
Hello guys, you have a typo in `src/lib.rs` on line `68`

```
//!         42,                 // Uniqe piont ID
```
should be
```
//!         42,                 // Unique point ID
```

### PR DESCRIPTION
**Pull request by JojiiOfficial**
Fixes #202

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -65,7 +65,7 @@
 //!# -> Result<(), QdrantError> {
 //! let points = vec![
 //!     PointStruct::new(
-//!         42,                 // Uniqe piont ID
+//!         42,                 // Uniqe point ID
```
Comment (timvisee) [inline src/lib.rs:68]: Two fixes in one go :smiley: 

```suggestion
//!         42,                 // Unique point ID
```

**Review by timvisee — APPROVED** [review]
